[workspace]
members = ["sourcier-core"]
resolver = "3"
[workspace.dependencies]
memchr = { version = "2.7.4" }
serde = { version = "1.0", features = ["derive"] }
insta = { version = "1.42", features = ["json", "yaml"] }
trybuild = "1.0"
